name: SBOM and Vulnerability Scan
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  security-events: write
  actions: read

jobs:
  security_analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: create SBOM
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          output-file: sbom.json
          
      - name: Scan SBOM for Vulnerabilities with Grype
        uses: anchore/scan-action@v6
        with:
          sbom: sbom.json
          severity-cutoff: critical 
          fail-build: true
          
      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-sbom-artifact
          path: sbom.json
          retention-days: 5
